### ISSUE TITLE
running code without CUDA

### ISSUE THREAD

**Issue by FrancescaCi** [sjmoran/CURL#26]
Hi, 
I am trying to perform the test of your great project with the default images, but I need to perform on CPU, is it possible? and if it is yes, How?
For now I removed net.cuda(), and I put cpu on checkpoint = torch.load(checkpoint_filepath, map_location='cpu'), but the result of batch-size is 0, what can be the problem?

Thank you so much for your support!

**Comment by sjmoran** [comment]
Thank you for your interest in this work. It should be possible to run on CPU, although it might be quite slow. The calls that you have made i.e. remove net.cuda() and loading onto the cpu would have been my suggestion, but they appear not to have worked for you. Can you provide more detail please on the batch size 0 issue? Does this mean you getting back no data from the data loader?

**Comment by FrancescaCi** [comment]
Sure, The error is that one:
2022-02-09 14:19:26,374 INFO ##############################
2022-02-09 14:19:26,374 INFO Loading Adobe5k dataset ...
/home/francescadigiacomo/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 10 worker processes in total. Our suggested max number of worker in current system is 8, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
2022-02-09 14:19:26,375 INFO Performing inference with images in directory: ./adobe5k_dpe/
0
0
Traceback (most recent call last):
  File "main.py", line 352, in <module>
    main()
  File "main.py", line 128, in main
    inference_evaluator.evaluate(net, epoch=0)
  File "path/CURL/metric.py", line 153, in evaluate
    psnr_avg = psnr_avg / num_batches
ZeroDivisionError: float division by zero

**Comment by sjmoran** [comment]
I don't think this is an issue with running on the CPU. I believe it is to do with the structure of the inference directory. Can you please show the directory structure you have.

**Comment by FrancescaCi** [comment]
![5c70bbb3-a420-4e92-bac2-eba9790810be](https://user-images.githubusercontent.com/98951708/153210645-462c2757-816f-41a2-bd7a-7fd18767d0d2.PNG)

**Comment by FrancescaCi** [comment]
![Screenshot from 2022-02-09 14-29-28](https://user-images.githubusercontent.com/98951708/153210964-545a0dd7-b685-4958-9f44-1b963b320df2.png)

**Comment by sjmoran** [comment]
Thanks, can you also share the command you enter at the command line?

**Comment by FrancescaCi** [comment]
python3 main.py --inference_img_dirpath=./adobe5k_dpe/ --checkpoint_filepath=./pretrained_models/adobe_dpe/curl_validpsnr_23.073045286204017_validloss_0.0701291635632515_testpsnr_23.584083321292365_testloss_0.061363041400909424_epoch_510_model.pt

the difference with your suggestion is :/pretrained_models/adobe_dpe, because from git clone there are not the models inside pretrained_models

**Comment by sjmoran** [comment]
Got it, so I suspect I know the problem here. The code will look in curl_example_test_input for the images. It does this as in line 298 of data.py it is looking for a directory with "input" in the name - see [here](https://github.com/sjmoran/CURL/blob/919e519717b66e14d92ac6fa404c328ee3f254a5/data.py#L298). The images listed in images_inference.txt are not those in curl_example_test_input. To get this to work you should add into images_inference.txt those image file names that are in curl_example_test_input, removing the extensions.

**Comment by FrancescaCi** [comment]
Good, I will try you suggestions, thank you so much. Another questions, please. From you point of view, is it possible to use your model and apply them with a cpp implementation? Do you know if could be some issue moving from  python to cpp for your implementation?

**Comment by FrancescaCi** [comment]
> Sorry, I followed your suggestion but it seems to not work with the same result
![image](https://user-images.githubusercontent.com/98951708/153224053-e26529d6-e11a-4e85-884f-0f4ac8b75bb4.png)
![image](https://user-images.githubusercontent.com/98951708/153224108-d2e39147-3950-4bfa-ae3f-5cf8e8e70bb5.png)
![image](https://user-images.githubusercontent.com/98951708/153224165-053baca2-da55-408e-8e68-06e8d41105c3.png)

**Comment by FrancescaCi** [comment]
Thank you so much, but another problem occurred:
![image](https://user-images.githubusercontent.com/98951708/153226998-f30c1c5e-ba99-4e02-8184-dc3525487286.png)
![image](https://user-images.githubusercontent.com/98951708/153227080-f5691871-6446-4599-a5f7-4b90cfacec0e.png)
What do you think can be the issue?

**Comment by sjmoran** [comment]
What is the contents of img_filepath? Try and print it out to debug: print(img_filepath)

**Comment by FrancescaCi** [comment]
![image](https://user-images.githubusercontent.com/98951708/153231410-aad54cfe-f409-4886-aa9d-caffd5ba96ec.png)
it seems correct, but it returns the same issue

**Comment by sjmoran** [comment]
input_img_filepath has no root directory or path attached to it, so the loading function is unable to find the image

**Comment by sjmoran** [comment]
> Good, I will try you suggestions, thank you so much. Another questions, please. From you point of view, is it possible to use your model and apply them with a cpp implementation? Do you know if could be some issue moving from python to cpp for your implementation?

Yes, my suggested approach is to compile the model to Onnx and that will allow you to inference it from a cpp application. More detail [here](https://www.analyticsvidhya.com/blog/2021/04/porting-a-pytorch-model-to-c/).

**Comment by FrancescaCi** [comment]
Hi, 
thank you so much for your suggestions about Cpp implementation, for the path problem, I tried this command, forcing the directory from the command but it is not able to find the image, where can I include the directory? 
python3 main.py --inference_img_dirpath=/home/francescadigiacomo/inventia-image-tools/TEST_IMAGE_ENHANCEMENT/linux_inventia/CURL/adobe5k_dpe/ --checkpoint_filepath=/home/francescadigiacomo/inventia-image-tools/TEST_IMAGE_ENHANCEMENT/linux_inventia/CURL/pretrained_models/curl_validpsnr_23.073045286204017_validloss_0.0701291635632515_testpsnr_23.584083321292365_testloss_0.061363041400909424_epoch_510_model.pt

![image](https://user-images.githubusercontent.com/98951708/153378914-5c6e3438-4f93-4fc1-92a4-eb61deedb7b1.png)

**Comment by sjmoran** [comment]
Closing due to inactivity
